@id = 106

# GET WORK ITEM
GET https://dev.azure.com/{{organization}}/{{project}}/_apis/wit/workitems/{{id}}?$expand=all&api-version=5.1 HTTP/1.1
content-type: application/json
Authorization: {{authorizationToken}}

###

# GET WORK ITEMS BATCH
POST https://dev.azure.com/{{organization}}/{{project}}/_apis/wit/workitemsbatch?api-version=5.1 HTTP/1.1
content-type: application/json
Authorization: {{authorizationToken}}

{
  "ids": [68, 109], 
  "asOf": "2020-05-15",
  "$expand": "All",
  "errorPolicy": "omit"
}
###

# GET WORK ITEMS
GET https://dev.azure.com/{{organization}}/{{project}}/_apis/wit/workitems?ids=68,109&asOf=2020-05-15&$expand=All&api-version=5.1 HTTP/1.1
content-type: application/json
Authorization: {{authorizationToken}}
###


### CREATE WORK ITEM
POST https://dev.azure.com/{{organization}}/{{project}}/_apis/wit/workitems/$Bug?api-version=5.0 HTTP/1.1
content-type: application/json-patch+json
Authorization: {{authorizationToken}}

[
  {
    "op": "add",
    "path": "/fields/System.Title",
    "from": null,
    "value": "Sample Bug"
  }
]

###

### UPDATE A FIELD
PATCH https://dev.azure.com/{{organization}}/_apis/wit/workitems/{{id}}?api-version=5.0 HTTP/1.1
content-type: application/json-patch+json
Authorization: {{authorizationToken}}

[
  {
    "op": "test",
    "path": "/rev",
    "value": 1
  },
  {
    "op": "add",
    "path": "/fields/System.Title",
    "value": "hello World"
  }
]

### CHANGE WORK ITEM TYPE
PATCH https://dev.azure.com/{{organization}}/_apis/wit/workitems/{{id}}?api-version=5.1 HTTP/1.1
content-type: application/json-patch+json
Authorization: {{authorizationToken}}

[
 {
    "op": "add",
    "path": "/fields/System.WorkItemType",
    "value": "Task"
  },
  {
    "op": "add",
    "path": "/fields/System.State",
    "value": "New"
  }
]

### ADD A LINK
PATCH https://dev.azure.com/{{organization}}/_apis/wit/workitems/{{id}}?api-version=5.1 HTTP/1.1
content-type: application/json-patch+json
Authorization: {{authorizationToken}}

[
  {
    "op": "test",
    "path": "/rev",
    "value": 5
  },
  {
    "op": "add",
    "path": "/fields/System.State",
    "value": "Closed"
  }
]