@id = 8

# GET WORK ITEM
GET https://dev.azure.com/{{organization}}/{{project}}/_apis/wit/workitems/{{id}}?api-version=5.1 HTTP/1.1
content-type: application/json
Authorization: {{authorizationToken}}

###


### CREATE WORK ITEM
POST https://dev.azure.com/{{organization}}/{{project}}/_apis/wit/workitems/$Bug?api-version=5.1 HTTP/1.1
content-type: application/json-patch+json
Authorization: {{authorizationToken}}

[
  {
    "op": "add",
    "path": "/fields/System.Title",
    "from": null,
    "value": "Sample Bug"
  }
]

### UPDATE A FIELD
PATCH https://dev.azure.com/{{organization}}/_apis/wit/workitems/{{id}}?api-version=5.1 HTTP/1.1
content-type: application/json-patch+json
Authorization: {{authorizationToken}}

[
  {
    "op": "test",
    "path": "/rev",
    "value": 5
  },
  {
    "op": "add",
    "path": "/fields/System.State",
    "value": "Closed"
  }
]

### CHANGE WORK ITEM TYPE
PATCH https://dev.azure.com/{{organization}}/_apis/wit/workitems/{{id}}?api-version=5.1 HTTP/1.1
content-type: application/json-patch+json
Authorization: {{authorizationToken}}

[
 {
    "op": "add",
    "path": "/fields/System.WorkItemType",
    "value": "Task"
  },
  {
    "op": "add",
    "path": "/fields/System.State",
    "value": "New"
  }
]