@processId = 9575d6ea-b90d-46b7-b9c2-a27570d43714

# LIST WORK ITEM TYPES
GET https://dev.azure.com/{{organization}}/_apis/work/processes/{{processId}}/workitemtypes?$expand=All&api-version=6.0-preview.2 HTTP/1.1
content-type: application/json
Authorization: {{authorizationToken}}

###